Repository GratefulTogether/gratefultogether-ui, pull requests merged in 2023-09, with the labels that each got.

#53 Deployed on vercel
  .vercel/README.txt
  .vercel/project.json
Labels: enhancement

#56 add correct link for post request
  src/components/Form/Form.js
Labels: bug

#61 Refactor/styling
  .gitignore
  .vercel/project.json
  public/index.html
  src/components/App/App.css
  src/components/App/App.js
  src/components/CalendarModal/CalendarModal.css
  src/components/CalendarModal/CalendarModal.js
  src/components/Cards/Cards.css
  src/components/Cards/Cards.js
  src/components/Datepage/Datepage.css
  src/components/Datepage/Datepage.js
  src/components/EntriesContainer/EntriesContainer.css
  src/components/EntriesContainer/EntriesContainer.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Form/Form.css
  src/components/Form/Form.js
  src/components/Homepage/Homepage.css
  src/components/Homepage/Homepage.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/components/NewDateForm/NewDateForm.css
  src/components/NewDateForm/NewDateForm.js
  src/index.css
Labels: enhancement

#62 Test/assistivemsg
  cypress/e2e/404.cy.js
  cypress/e2e/500.cy.js
  cypress/e2e/assitivemsg.cy.js
  cypress/e2e/mainel.cy.js
  cypress/e2e/modal.cy.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/today.json
  src/components/App/App.js
  src/components/Homepage/Homepage.js
Labels: testing

#64 Resolve errors
  .vercel/project.json
  cypress/e2e/404.cy.js
  cypress/e2e/mainel.cy.js
  cypress/e2e/modal.cy.js
  src/components/App/App.js
  src/components/EntriesContainer/EntriesContainer.js
Labels: bug, help wanted, testing
